# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'additionalItemInfo.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(418, 601)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.personsCart = QtWidgets.QFrame(self.centralwidget)
        self.personsCart.setMinimumSize(QtCore.QSize(400, 50))
        self.personsCart.setMaximumSize(QtCore.QSize(16777215, 50))
        self.personsCart.setStyleSheet("background-color: rgb(245, 245, 245);\n"
"border-color: rgb(20, 20, 20);")
        self.personsCart.setFrameShape(QtWidgets.QFrame.Box)
        self.personsCart.setFrameShadow(QtWidgets.QFrame.Plain)
        self.personsCart.setLineWidth(2)
        self.personsCart.setObjectName("personsCart")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.personsCart)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.personsCart)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout_11.addWidget(self.personsCart)
        self.CenterFrame = QtWidgets.QFrame(self.centralwidget)
        self.CenterFrame.setMinimumSize(QtCore.QSize(400, 400))
        self.CenterFrame.setStyleSheet("background-color: rgb(245, 245, 245);\n"
"border-color: rgb(20, 20, 20);")
        self.CenterFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.CenterFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.CenterFrame.setLineWidth(2)
        self.CenterFrame.setObjectName("CenterFrame")
        self.gridLayout = QtWidgets.QGridLayout(self.CenterFrame)
        self.gridLayout.setContentsMargins(-1, -1, -1, 5)
        self.gridLayout.setObjectName("gridLayout")
        self.CenterScrollArea = QtWidgets.QScrollArea(self.CenterFrame)
        self.CenterScrollArea.setStyleSheet("background-color: rgb(245, 245, 245);\n"
"border-color: rgb(20, 20, 20);")
        self.CenterScrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.CenterScrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.CenterScrollArea.setWidgetResizable(True)
        self.CenterScrollArea.setObjectName("CenterScrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 402, 450))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.toolButton_4 = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        self.toolButton_4.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("table.JPG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_4.setIcon(icon)
        self.toolButton_4.setIconSize(QtCore.QSize(370, 200))
        self.toolButton_4.setAutoRaise(True)
        self.toolButton_4.setObjectName("toolButton_4")
        self.verticalLayout_9.addWidget(self.toolButton_4)
        self.verticalLayout.addLayout(self.verticalLayout_9)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setMinimumSize(QtCore.QSize(0, 20))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_10.addWidget(self.label_3)
        self.toolButton_6 = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("location.JPG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_6.setIcon(icon1)
        self.toolButton_6.setIconSize(QtCore.QSize(180, 180))
        self.toolButton_6.setAutoRaise(True)
        self.toolButton_6.setObjectName("toolButton_6")
        self.verticalLayout_10.addWidget(self.toolButton_6)
        self.horizontalLayout_6.addLayout(self.verticalLayout_10)
        self.toolButton_5 = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("nutrution facts.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_5.setIcon(icon2)
        self.toolButton_5.setIconSize(QtCore.QSize(150, 200))
        self.toolButton_5.setAutoRaise(True)
        self.toolButton_5.setObjectName("toolButton_5")
        self.horizontalLayout_6.addWidget(self.toolButton_5)
        self.gridLayout_2.addLayout(self.horizontalLayout_6, 1, 0, 1, 1)
        self.CenterScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.CenterScrollArea, 0, 0, 1, 1)
        self.verticalLayout_11.addWidget(self.CenterFrame)
        self.BottomMenu = QtWidgets.QFrame(self.centralwidget)
        self.BottomMenu.setMinimumSize(QtCore.QSize(400, 80))
        self.BottomMenu.setMaximumSize(QtCore.QSize(16777215, 100))
        self.BottomMenu.setStyleSheet("background-color: rgb(245, 245, 245);\n"
"border-color: rgb(20, 20, 20);")
        self.BottomMenu.setFrameShape(QtWidgets.QFrame.Box)
        self.BottomMenu.setLineWidth(2)
        self.BottomMenu.setObjectName("BottomMenu")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.BottomMenu)
        self.horizontalLayout_2.setSpacing(75)
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setContentsMargins(1, 1, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.toolButton_2 = QtWidgets.QToolButton(self.BottomMenu)
        self.toolButton_2.setMaximumSize(QtCore.QSize(50, 70))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("scan button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_2.setIcon(icon3)
        self.toolButton_2.setIconSize(QtCore.QSize(50, 50))
        self.toolButton_2.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_2.setAutoRaise(True)
        self.toolButton_2.setObjectName("toolButton_2")
        self.horizontalLayout_2.addWidget(self.toolButton_2)
        self.toolButton_3 = QtWidgets.QToolButton(self.BottomMenu)
        self.toolButton_3.setMaximumSize(QtCore.QSize(50, 70))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("square button2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_3.setIcon(icon4)
        self.toolButton_3.setIconSize(QtCore.QSize(60, 60))
        self.toolButton_3.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_3.setAutoRaise(True)
        self.toolButton_3.setObjectName("toolButton_3")
        self.horizontalLayout_2.addWidget(self.toolButton_3)
        self.toolButton = QtWidgets.QToolButton(self.BottomMenu)
        self.toolButton.setMaximumSize(QtCore.QSize(50, 70))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("menu button2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon5)
        self.toolButton.setIconSize(QtCore.QSize(50, 50))
        self.toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton.setAutoRaise(True)
        self.toolButton.setObjectName("toolButton")
        self.horizontalLayout_2.addWidget(self.toolButton)
        self.verticalLayout_11.addWidget(self.BottomMenu)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 418, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Milk 2% 4 Litre"))
        self.label_3.setText(_translate("MainWindow", "Location:"))
        self.toolButton_6.setText(_translate("MainWindow", "..."))
        self.toolButton_5.setText(_translate("MainWindow", "..."))
        self.toolButton_2.setText(_translate("MainWindow", "Scan"))
        self.toolButton_3.setText(_translate("MainWindow", "Cart"))
        self.toolButton.setText(_translate("MainWindow", "Menu"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

