# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainPage.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(418, 588)
        MainWindow.setStyleSheet("background-color: rgb(245, 245, 245);\n"
"border-color: rgb(40, 40, 40);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.personsCart = QtWidgets.QFrame(self.centralwidget)
        self.personsCart.setMinimumSize(QtCore.QSize(400, 50))
        self.personsCart.setMaximumSize(QtCore.QSize(16777215, 50))
        self.personsCart.setStyleSheet("background-color: rgb(245, 245, 245);\n"
"border-color: rgb(40, 40, 40);")
        self.personsCart.setFrameShape(QtWidgets.QFrame.Box)
        self.personsCart.setLineWidth(2)
        self.personsCart.setObjectName("personsCart")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.personsCart)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.personsCart)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout_2.addWidget(self.personsCart)
        self.CenterFrame = QtWidgets.QFrame(self.centralwidget)
        self.CenterFrame.setMinimumSize(QtCore.QSize(400, 400))
        self.CenterFrame.setStyleSheet("background-color: rgb(245, 245, 245);\n"
"border-color: rgb(20, 20, 20);")
        self.CenterFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.CenterFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.CenterFrame.setLineWidth(2)
        self.CenterFrame.setObjectName("CenterFrame")
        self.gridLayout = QtWidgets.QGridLayout(self.CenterFrame)
        self.gridLayout.setContentsMargins(-1, -1, -1, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.CenterFrame)
        self.frame.setMinimumSize(QtCore.QSize(380, 30))
        self.frame.setStyleSheet("background-color: rgb(245, 245, 245);\n"
"border-color: rgb(20, 20, 20);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2, QtCore.Qt.AlignRight)
        self.gridLayout.addWidget(self.frame, 1, 0, 1, 1)
        self.CenterScrollArea = QtWidgets.QScrollArea(self.CenterFrame)
        self.CenterScrollArea.setStyleSheet("background-color: rgb(245, 245, 245);\n"
"border-color: rgb(20, 20, 20);")
        self.CenterScrollArea.setFrameShape(QtWidgets.QFrame.Box)
        self.CenterScrollArea.setLineWidth(2)
        self.CenterScrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.CenterScrollArea.setWidgetResizable(True)
        self.CenterScrollArea.setObjectName("CenterScrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 357, 520))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 100))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 100))
        self.groupBox.setStyleSheet("background-color: rgb(245, 245, 245);\n"
"border-color: rgb(20, 20, 20);")
        self.groupBox.setFlat(True)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.toolButton_4 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_4.setMaximumSize(QtCore.QSize(60, 60))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("milk.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_4.setIcon(icon)
        self.toolButton_4.setIconSize(QtCore.QSize(60, 60))
        self.toolButton_4.setAutoRaise(True)
        self.toolButton_4.setObjectName("toolButton_4")
        self.horizontalLayout_4.addWidget(self.toolButton_4)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.toolButton_9 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.toolButton_9.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("info button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_9.setIcon(icon1)
        self.toolButton_9.setAutoRaise(True)
        self.toolButton_9.setObjectName("toolButton_9")
        self.verticalLayout_3.addWidget(self.toolButton_9, QtCore.Qt.AlignRight|QtCore.Qt.AlignTop)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_4)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_4 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_4.setMinimumSize(QtCore.QSize(0, 100))
        self.groupBox_4.setMaximumSize(QtCore.QSize(16777215, 100))
        self.groupBox_4.setFlat(True)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.toolButton_5 = QtWidgets.QToolButton(self.groupBox_4)
        self.toolButton_5.setMaximumSize(QtCore.QSize(60, 60))
        self.toolButton_5.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("brocolli.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_5.setIcon(icon2)
        self.toolButton_5.setIconSize(QtCore.QSize(60, 60))
        self.toolButton_5.setAutoRaise(True)
        self.toolButton_5.setObjectName("toolButton_5")
        self.horizontalLayout_6.addWidget(self.toolButton_5)
        self.label_5 = QtWidgets.QLabel(self.groupBox_4)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.toolButton_10 = QtWidgets.QToolButton(self.groupBox_4)
        self.toolButton_10.setIcon(icon1)
        self.toolButton_10.setAutoRaise(True)
        self.toolButton_10.setObjectName("toolButton_10")
        self.verticalLayout_4.addWidget(self.toolButton_10, QtCore.Qt.AlignRight|QtCore.Qt.AlignTop)
        self.label_6 = QtWidgets.QLabel(self.groupBox_4)
        self.label_6.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6)
        self.horizontalLayout_6.addLayout(self.verticalLayout_4)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_6)
        self.verticalLayout.addWidget(self.groupBox_4)
        self.groupBox_3 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_3.setMinimumSize(QtCore.QSize(0, 100))
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 100))
        self.groupBox_3.setFlat(True)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_8.setSpacing(9)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.toolButton_6 = QtWidgets.QToolButton(self.groupBox_3)
        self.toolButton_6.setMaximumSize(QtCore.QSize(60, 60))
        self.toolButton_6.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("chicken.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_6.setIcon(icon3)
        self.toolButton_6.setIconSize(QtCore.QSize(60, 60))
        self.toolButton_6.setAutoRaise(True)
        self.toolButton_6.setObjectName("toolButton_6")
        self.horizontalLayout_11.addWidget(self.toolButton_6)
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_11.addWidget(self.label_7)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.toolButton_11 = QtWidgets.QToolButton(self.groupBox_3)
        self.toolButton_11.setIcon(icon1)
        self.toolButton_11.setAutoRaise(True)
        self.toolButton_11.setObjectName("toolButton_11")
        self.verticalLayout_6.addWidget(self.toolButton_11, QtCore.Qt.AlignRight|QtCore.Qt.AlignTop)
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_6.addWidget(self.label_8)
        self.horizontalLayout_11.addLayout(self.verticalLayout_6)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_11)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox_2 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 100))
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 100))
        self.groupBox_2.setFlat(True)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.toolButton_7 = QtWidgets.QToolButton(self.groupBox_2)
        self.toolButton_7.setMaximumSize(QtCore.QSize(60, 60))
        self.toolButton_7.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("bee movie.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_7.setIcon(icon4)
        self.toolButton_7.setIconSize(QtCore.QSize(60, 60))
        self.toolButton_7.setAutoRaise(True)
        self.toolButton_7.setObjectName("toolButton_7")
        self.horizontalLayout_12.addWidget(self.toolButton_7)
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_12.addWidget(self.label_10)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.toolButton_12 = QtWidgets.QToolButton(self.groupBox_2)
        self.toolButton_12.setIcon(icon1)
        self.toolButton_12.setAutoRaise(True)
        self.toolButton_12.setObjectName("toolButton_12")
        self.verticalLayout_7.addWidget(self.toolButton_12, QtCore.Qt.AlignRight|QtCore.Qt.AlignTop)
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_7.addWidget(self.label_9)
        self.horizontalLayout_12.addLayout(self.verticalLayout_7)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_12)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_5 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_5.setMinimumSize(QtCore.QSize(0, 100))
        self.groupBox_5.setMaximumSize(QtCore.QSize(16777215, 100))
        self.groupBox_5.setFlat(True)
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.toolButton_8 = QtWidgets.QToolButton(self.groupBox_5)
        self.toolButton_8.setMaximumSize(QtCore.QSize(60, 60))
        self.toolButton_8.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("secret.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_8.setIcon(icon5)
        self.toolButton_8.setIconSize(QtCore.QSize(60, 60))
        self.toolButton_8.setAutoRaise(True)
        self.toolButton_8.setObjectName("toolButton_8")
        self.horizontalLayout_13.addWidget(self.toolButton_8)
        self.label_12 = QtWidgets.QLabel(self.groupBox_5)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_13.addWidget(self.label_12)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.toolButton_13 = QtWidgets.QToolButton(self.groupBox_5)
        self.toolButton_13.setIcon(icon1)
        self.toolButton_13.setAutoRaise(True)
        self.toolButton_13.setObjectName("toolButton_13")
        self.verticalLayout_8.addWidget(self.toolButton_13, QtCore.Qt.AlignRight|QtCore.Qt.AlignTop)
        self.label_11 = QtWidgets.QLabel(self.groupBox_5)
        self.label_11.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_8.addWidget(self.label_11)
        self.horizontalLayout_13.addLayout(self.verticalLayout_8)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_13)
        self.verticalLayout.addWidget(self.groupBox_5)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.CenterScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.CenterScrollArea, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.CenterFrame)
        self.BottomMenu = QtWidgets.QFrame(self.centralwidget)
        self.BottomMenu.setMinimumSize(QtCore.QSize(400, 80))
        self.BottomMenu.setMaximumSize(QtCore.QSize(16777215, 100))
        self.BottomMenu.setStyleSheet("background-color: rgb(245, 245, 245);\n"
"border-color: rgb(20, 20, 20);")
        self.BottomMenu.setFrameShape(QtWidgets.QFrame.Box)
        self.BottomMenu.setLineWidth(2)
        self.BottomMenu.setObjectName("BottomMenu")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.BottomMenu)
        self.horizontalLayout_2.setSpacing(75)
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setContentsMargins(1, 0, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.toolButton_2 = QtWidgets.QToolButton(self.BottomMenu)
        self.toolButton_2.setMaximumSize(QtCore.QSize(50, 70))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("scan button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_2.setIcon(icon6)
        self.toolButton_2.setIconSize(QtCore.QSize(50, 50))
        self.toolButton_2.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_2.setAutoRaise(True)
        self.toolButton_2.setObjectName("toolButton_2")
        self.horizontalLayout_2.addWidget(self.toolButton_2)
        self.toolButton_3 = QtWidgets.QToolButton(self.BottomMenu)
        self.toolButton_3.setMaximumSize(QtCore.QSize(50, 70))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("square button2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_3.setIcon(icon7)
        self.toolButton_3.setIconSize(QtCore.QSize(60, 60))
        self.toolButton_3.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_3.setAutoRaise(True)
        self.toolButton_3.setObjectName("toolButton_3")
        self.horizontalLayout_2.addWidget(self.toolButton_3)
        self.toolButton = QtWidgets.QToolButton(self.BottomMenu)
        self.toolButton.setMaximumSize(QtCore.QSize(50, 70))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("menu button2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon8)
        self.toolButton.setIconSize(QtCore.QSize(50, 50))
        self.toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton.setAutoRaise(True)
        self.toolButton.setObjectName("toolButton")
        self.horizontalLayout_2.addWidget(self.toolButton)
        self.verticalLayout_2.addWidget(self.BottomMenu)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Michael Mogentale\'s Cart"))
        self.label_2.setText(_translate("MainWindow", "Total: $43.50"))
        self.groupBox.setTitle(_translate("MainWindow", "Milk 2%"))
        self.toolButton_4.setText(_translate("MainWindow", "..."))
        self.label_3.setText(_translate("MainWindow", "Quantity: 2"))
        self.label_4.setText(_translate("MainWindow", "$10.00"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Broccoli"))
        self.label_5.setText(_translate("MainWindow", "Quantity: 2"))
        self.toolButton_10.setText(_translate("MainWindow", "..."))
        self.label_6.setText(_translate("MainWindow", "$5.25"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Free Range Chicken Breast"))
        self.label_7.setText(_translate("MainWindow", "Quantity: 1"))
        self.toolButton_11.setText(_translate("MainWindow", "..."))
        self.label_8.setText(_translate("MainWindow", "$25.75"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Bee Movie"))
        self.label_10.setText(_translate("MainWindow", "Quantity: 1"))
        self.toolButton_12.setText(_translate("MainWindow", "..."))
        self.label_9.setText(_translate("MainWindow", "$10.00"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Mike\'s secret purchase"))
        self.label_12.setText(_translate("MainWindow", "Quantity: 3"))
        self.toolButton_13.setText(_translate("MainWindow", "..."))
        self.label_11.setText(_translate("MainWindow", "$0.00"))
        self.toolButton_2.setText(_translate("MainWindow", "Scan"))
        self.toolButton_3.setText(_translate("MainWindow", "Cart"))
        self.toolButton.setText(_translate("MainWindow", "Menu"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

